# Generated by Django 4.1.7 on 2023-02-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesinais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirmation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
