# Generated by Django 4.1.7 on 2023-02-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesinais', '0002_customuser_confirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('background', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'dados',
            },
        ),
    ]
