# Generated by Django 4.1.7 on 2023-02-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesinais', '0003_dados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sinais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sinais',
            },
        ),
    ]
