# Generated by Django 4.1.7 on 2023-03-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesinais', '0004_sinais'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinais',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
